# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required
---
version: 2
# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - |
        # check if README has changed between successive commits
        if git rev-parse HEAD^ >/dev/null 2>&1; then
          if git diff --quiet HEAD^ -- README.md; then
            echo "No change to README.md. Exiting."
            exit 183
          fi
        fi
    pre_build:
      - |
        python -m sphinx -b linkcheck . $READTHEDOCS_OUTPUT/linkcheck
    pre_install:
      # <-- This runs your script before Sphinx builds
      - python strip_toc.py
sphinx:
  configuration: conf.py
  fail_on_warning: true
formats:
  - epub
  - pdf
python:
  install:
    # Install our python packages before building the docs
    - requirements: requirements.txt
