# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required
---
version: 2
# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      # Cancel building pull requests when there aren't changed in the
      # README.md file.
      # If there are no changes (git diff exits with 0) we force the command
      # to return with 183.
      # This is a special exit code on Read the Docs that will cancel the
      # build immediately.
      - |
        if git diff --quiet origin/main -- README.md; then
          exit 183
        fi
    pre_build: >
      - python -m sphinx -b linkcheck -D linkcheck_timeout=1 README.md

        $READTHEDOCS_OUTPUT/linkcheck
    pre_install:
      # <-- This runs your script before Sphinx builds
      - python strip_toc.py
sphinx:
  configuration: conf.py
  fail_on_warning: true
formats:
  - epub
  - pdf
python:
  install:
    # Install our python packages before building the docs
    - requirements: requirements.txt
