# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
---
version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - |
        # Skip build if only non-visible files changed
        if git rev-parse HEAD^ >/dev/null 2>&1; then
          changed_files="README.md index.rst conf.py .readthedocs.yaml"
          jpg_files=$(git ls-files | grep -E '\.jpe?g$')
          if git diff --quiet HEAD^ -- $changed_files $jpg_files \
            && ! git tag --points-at HEAD | grep . >/dev/null; then
            echo "No change in visible artifacts or new version. Exiting."
            exit 183
          fi
         fi
    pre_install:
      - python strip_toc.py
      - python copytostatic.py
      - python -m pip install --upgrade --no-cache-dir python-dotenv
      - |
        months="January.md February.md March.md April.md May.md June.md \
                July.md August.md September.md October.md November.md \
                December.md"
        python rewritelinks.py --gh-markdown-to-rtd start.md $months
python:
  install:
    - requirements: requirements.txt
sphinx:
  configuration: conf.py
  fail_on_warning: true
formats:
  - epub
  - pdf
