class ConfigConstants:
    """Static class containing all configuration constants from config.env"""
    
    # Project config
    PROJECT = "PROJECT"
    LOGGING = "LOGGING"
    YEAR = "YEAR"
    
    # Github config
    REPO_OWNER = "REPO_OWNER"
    REPO_NAME = "REPO_NAME"
    
    # Overlay icon config
    ICON_FILE = "ICON_FILE"
    ICON_SIZE = "ICON_SIZE"
    ICON_OFFSET = "ICON_OFFSET"
    ICON_COMMENT = "ICON_COMMENT"
    
    # Video files config
    COMPACT_FILE = "COMPACT_FILE"
    VIDEOS_FILE = "VIDEOS_FILE"
    
    # Curl config
    GAP_BW_REQS = "GAP_BW_REQS"
    CURL_MAX_RETRIES = "CURL_MAX_RETRIES"
    CURL_INITIAL_RETRY_DELAY = "CURL_INITIAL_RETRY_DELAY"
    CURL_CONNECT_TIMEOUT = "CURL_CONNECT_TIMEOUT"
    CURL_MAX_TIME = "CURL_MAX_TIME"
    
    # Transcription config
    TRANSCRIBE_VIDEOS = "TRANSCRIBE_VIDEOS"
    TRANSCRIBE_LOCALLY = "TRANSCRIBE_LOCALLY"
    USE_FASTER_WHISPER = "USE_FASTER_WHISPER"
    ENABLE_FAILOVER_MODE = "ENABLE_FAILOVER_MODE"
    
    # ASR LLM config
    ASR_LLM_API_KEY = "ASR_LLM_API_KEY"
    ASR_LLM_BASE_URL = "ASR_LLM_BASE_URL"
    ASR_LLM_ENDPOINT = "ASR_LLM_ENDPOINT"
    ASR_LLM_MODEL = "ASR_LLM_MODEL"
    ASR_LOCAL_MODEL = "ASR_LOCAL_MODEL"
    ASR_INITIAL_PROMPT = "ASR_INITIAL_PROMPT"
    ASR_CARRY_INITIAL_PROMPT = "ASR_CARRY_INITIAL_PROMPT"
    ASR_BEAM_SIZE = "ASR_BEAM_SIZE"
    
    # YouTube config
    YT_DLP_RETRIES = "YT_DLP_RETRIES"
    YT_DLP_SOCKET_TIMEOUT = "YT_DLP_SOCKET_TIMEOUT"
    CAPTIONS_OUTPUT_DIR = "CAPTIONS_OUTPUT_DIR"
    
    # AI config
    TEMPERATURE = "TEMPERATURE"
    TEXT_LLM_API_KEY = "TEXT_LLM_API_KEY"
    TEXT_LLM_BASE_URL = "TEXT_LLM_BASE_URL"
    TEXT_LLM_CHAT_ENDPOINT = "TEXT_LLM_CHAT_ENDPOINT"
    TEXT_LLM_MODEL = "TEXT_LLM_MODEL"
    
    # Prompt config
    SYSTEM_SUMMARY_PROMPT = "SYSTEM_SUMMARY_PROMPT"
    CHUNK_SUMMARY_PROMPT = "CHUNK_SUMMARY_PROMPT"
    FINAL_SUMMARY_PROMPT = "FINAL_SUMMARY_PROMPT"
    SUMMARY_IMAGE_META_PROMPT = "SUMMARY_IMAGE_META_PROMPT"
    CAPTION_PROMPT = "CAPTION_PROMPT"
    SUMMARY_ARTWORK_DETAILS_PROMPT = "SUMMARY_ARTWORK_DETAILS_PROMPT"
    
    # Content docs
    CONTENT_DOCS = "CONTENT_DOCS"
    
    # Image generation config
    AUTO_GENERATE_IMAGES = "AUTO_GENERATE_IMAGES"
    IMAGE_GENERATION_SCRIPT = "IMAGE_GENERATION_SCRIPT"
    DEEPINFRA_IMAGE_GENERATION_MODEL = "DEEPINFRA_IMAGE_GENERATION_MODEL"
    FALAI_IMAGE_GENERATION_MODEL = "FALAI_IMAGE_GENERATION_MODEL"
    
    # Art downloader config
    AUTO_DOWNLOAD_ART = "AUTO_DOWNLOAD_ART"
    ART_DOWNLOADER_DIR = "ART_DOWNLOADER_DIR"
    STOCK_PHOTO_SITES = "STOCK_PHOTO_SITES"
    SOCIAL_MEDIA_SITES = "SOCIAL_MEDIA_SITES"
    VERIFY_ART_IMAGES = "VERIFY_ART_IMAGES"
    ART_VERIFIER_SCRIPT = "ART_VERIFIER_SCRIPT"
    ART_METADATA_PROMPT = "ART_METADATA_PROMPT"
    IMAGE_CONTENT_VALIDATION = "IMAGE_CONTENT_VALIDATION"
    VECTOR_EMBEDDINGS_MODEL_API_KEY = "VECTOR_EMBEDDINGS_MODEL_API_KEY"
    VECTOR_EMBEDDINGS_BASE_URL = "VECTOR_EMBEDDINGS_BASE_URL"
    VECTOR_EMBEDDINGS_MODEL = "VECTOR_EMBEDDINGS_MODEL"
    FIND_ALTERNATE_IMAGES = "FIND_ALTERNATE_IMAGES"
