class ConfigConstants:
    """Static class containing all configuration constants from config.env and API key constants"""

    # Project config
    PROJECT = "PROJECT"
    LOGGING = "LOGGING"
    LOGGING_LEVEL = "LOGGING_LEVEL"
    YEAR = "YEAR"

    # Commands file
    COMMANDS_FILE = "COMMANDS_FILE"

    # Github config
    REPO_OWNER = "REPO_OWNER"
    REPO_NAME = "REPO_NAME"

    # Overlay icon config
    ICON_FILE = "ICON_FILE"
    ICON_SIZE = "ICON_SIZE"
    ICON_OFFSET = "ICON_OFFSET"
    ICON_COMMENT = "ICON_COMMENT"

    # Video files config
    COMPACT_FILE = "COMPACT_FILE"
    VIDEOS_FILE = "VIDEOS_FILE"

    # Curl config
    GAP_BW_REQS = "GAP_BW_REQS"
    CURL_MAX_RETRIES = "CURL_MAX_RETRIES"
    CURL_INITIAL_RETRY_DELAY = "CURL_INITIAL_RETRY_DELAY"
    CURL_CONNECT_TIMEOUT = "CURL_CONNECT_TIMEOUT"
    CURL_MAX_TIME = "CURL_MAX_TIME"
    CURL_RETRY_STATUS_CODES = "CURL_RETRY_STATUS_CODES"
    CURL_RETRY_HEADER_STATUS_CODES = "CURL_RETRY_HEADER_STATUS_CODES"

    # Transcription config
    TRANSCRIBE_VIDEOS = "TRANSCRIBE_VIDEOS"
    TRANSCRIBE_LOCALLY = "TRANSCRIBE_LOCALLY"
    USE_FASTER_WHISPER = "USE_FASTER_WHISPER"
    ENABLE_FAILOVER_MODE = "ENABLE_FAILOVER_MODE"

    # ASR LLM config
    ASR_LLM_API_KEY = "ASR_LLM_API_KEY"
    ASR_LLM_BASE_URL = "ASR_LLM_BASE_URL"
    ASR_LLM_ENDPOINT = "ASR_LLM_ENDPOINT"
    ASR_LLM_MODEL = "ASR_LLM_MODEL"
    ASR_LOCAL_MODEL = "ASR_LOCAL_MODEL"
    ASR_INITIAL_PROMPT = "ASR_INITIAL_PROMPT"
    ASR_CARRY_INITIAL_PROMPT = "ASR_CARRY_INITIAL_PROMPT"
    ASR_BEAM_SIZE = "ASR_BEAM_SIZE"

    # YouTube config
    YT_DLP_RETRIES = "YT_DLP_RETRIES"
    YT_DLP_SOCKET_TIMEOUT = "YT_DLP_SOCKET_TIMEOUT"
    CAPTIONS_OUTPUT_DIR = "CAPTIONS_OUTPUT_DIR"

    # AI config
    TEMPERATURE = "TEMPERATURE"
    TEXT_LLM_API_KEY = "TEXT_LLM_API_KEY"
    TEXT_LLM_BASE_URL = "TEXT_LLM_BASE_URL"
    TEXT_LLM_CHAT_ENDPOINT = "TEXT_LLM_CHAT_ENDPOINT"
    TEXT_LLM_MODEL = "TEXT_LLM_MODEL"

    # Prompt config
    SYSTEM_SUMMARY_PROMPT = "SYSTEM_SUMMARY_PROMPT"
    CHUNK_SUMMARY_PROMPT = "CHUNK_SUMMARY_PROMPT"
    FINAL_SUMMARY_PROMPT = "FINAL_SUMMARY_PROMPT"
    SUMMARY_IMAGE_META_PROMPT = "SUMMARY_IMAGE_META_PROMPT"
    SUMMARY_ARTWORK_DETAILS_PROMPT = "SUMMARY_ARTWORK_DETAILS_PROMPT"
    ART_DETAILS_AUGMENT_PROMPT = "ART_DETAILS_AUGMENT_PROMPT"

    # Content docs
    CONTENT_DOCS = "CONTENT_DOCS"

    # Image generation config
    AUTO_GENERATE_IMAGES = "AUTO_GENERATE_IMAGES"
    IMAGE_GENERATION_SCRIPT = "IMAGE_GENERATION_SCRIPT"
    DEEPINFRA_IMAGE_GENERATION_MODEL = "DEEPINFRA_IMAGE_GENERATION_MODEL"
    FALAI_IMAGE_GENERATION_MODEL = "FALAI_IMAGE_GENERATION_MODEL"

    # Art downloader config
    AUTO_DOWNLOAD_ART = "AUTO_DOWNLOAD_ART"
    ART_DOWNLOADER_DIR = "ART_DOWNLOADER_DIR"
    MIN_IMAGE_WIDTH = "MIN_IMAGE_WIDTH"
    MIN_IMAGE_HEIGHT = "MIN_IMAGE_HEIGHT"
    SEARCH_WIKIPEDIA = "SEARCH_WIKIPEDIA"
    STOCK_PHOTO_SITES = "STOCK_PHOTO_SITES"
    SOCIAL_MEDIA_SITES = "SOCIAL_MEDIA_SITES"
    USE_ART_DATABASE = "USE_ART_DATABASE"

    # Art verifier config
    VERIFY_ART_IMAGES = "VERIFY_ART_IMAGES"
    ART_VERIFIER_SCRIPT = "ART_VERIFIER_SCRIPT"
    ART_METADATA_PROMPT = "ART_METADATA_PROMPT"
    IMAGE_CONTENT_VALIDATION = "IMAGE_CONTENT_VALIDATION"
    FIND_ALTERNATE_IMAGES = "FIND_ALTERNATE_IMAGES"

    # Vector embeddings config
    VECTOR_EMBEDDINGS_MODEL_API_KEY = "VECTOR_EMBEDDINGS_MODEL_API_KEY"
    VECTOR_EMBEDDINGS_BASE_URL = "VECTOR_EMBEDDINGS_BASE_URL"
    VECTOR_EMBEDDINGS_MODEL = "VECTOR_EMBEDDINGS_MODEL"
    VECTOR_EMBEDDINGS_MODEL_DIMENSIONS = "VECTOR_EMBEDDINGS_MODEL_DIMENSIONS"

    # Metadata extraction config
    AUGMENT_META_DATA_PROMPT = "AUGMENT_META_DATA_PROMPT"
    AUGMENT_META_DATA_BATCH_SIZE = "AUGMENT_META_DATA_BATCH_SIZE"
    ART_RECORDS_CSV = "ART_RECORDS_CSV"
    ART_DATABASE = "ART_DATABASE"
    ART_DATABASE_HNSW_INDEX = "ART_DATABASE_HNSW_INDEX"
    ART_DATABASE_HNSW_SPACE = "ART_DATABASE_HNSW_SPACE"
    ART_DATABASE_HNSW_MAX_RESULTS = "ART_DATABASE_HNSW_MAX_RESULTS"
    EMBEDDABLE_COLUMNS = "EMBEDDABLE_COLUMNS"
    ROSARY_PROMPT = "ROSARY_PROMPT"
    CREATE_CAPTION_PROMPT = "CREATE_CAPTION_PROMPT"

    # API Key constants
    OPENAI_API_KEY = "OPENAI_API_KEY"
    SERP_API_KEY = "SERP_API_KEY"
    ZENSERP_API_KEY = "ZENSERP_API_KEY"
    IMGBB_API_KEY = "IMGBB_API_KEY"
    DEEPINFRA_API_KEY = "DEEPINFRA_API_KEY"
    DEEPSEEK_API_KEY = "DEEPSEEK_API_KEY"
