#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
require date markdown-toc
#shellcheck disable=SC1091
source ./vidmd.sh
usage() {
  echo "$0 month year"
  echo "month - month number (1 - 12)"
  echo "year - 4 digit year"
  exit 1
}

if ! isnumeric "$1"; then
  usage
fi
if ! isnumeric "$2"; then
  usage
fi
year="$2"
len=$((${#year}))
if [ "$len" -ne 4 ]; then
  usage
fi
month=$((10#$1))
if ((month < 1 || month > 12)); then
  usage
fi
if [ "$len" -ne 4 ]; then
  usage
fi

month="$(monthfromnumber "$((10#${month}))")"
monthmd="${month}${year}.md"
./compact "${month}" >| "${monthmd}" \
  && markdown-toc -i "${monthmd}"
sed -i '/\S/,$!d' "${monthmd}"
exit "$?"
