#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
require gen-toc
usage() {
  echo "$0 markdownfile"
  echo "markdownfile - the markdown file for which table of contents is to be generated"
  exit 1
}
if test $# -ne 1; then
  usage
fi
if test -d "$1"; then
  usage
fi

gen-toc --write "$1"
exit "$?"
