#!/usr/bin/env bash
require() {
  hash "$@" || exit
}
require mdl mdformat
declare -i exitcode=0
mdformat -- **/*.md
exitcode=$((exitcode + $?))
mdl -- **/*.md
exitcode=$((exitcode + $?))
exit "$exitcode"
