#!/usr/bin/env bash
for file in *.md; do
  while read -r line; do
    if [[ $line =~ Day([0-9]{1,2})\.jpg ]]; then
      num=${BASH_REMATCH[1]}
      formatted_num=$(printf "%03d" "$num")
      echo "${line/Day${num}.jpg/Day${formatted_num}.jpg}"
    else
      echo "$line"
    fi
  done < "$file" > "${file%.md}_formatted.md"
  mv "${file%.md}_formatted.md" "$file"
done
