---
name: Delete Old Workflow Runs
permissions:
  actions: write
on:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 3 AM UTC
  workflow_dispatch: # Allows manual trigger
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs older than N days
        uses: actions/github-script@v7
        with:
          script: |
            const retentionDays = 7; // adjust as needed
            const workflows = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            for (const workflow of workflows.data.workflows) {
              const runs = await github.paginate(
                github.rest.actions.listWorkflowRuns,
                {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: workflow.id,
                  per_page: 100,
                }
              );

              const now = new Date();
              for (const run of runs) {
                const runDate = new Date(run.created_at);
                const ageInDays = (now - runDate) / (1000 * 60 * 60 * 24);
                if (ageInDays > retentionDays && run.status === 'completed') {
                  await github.rest.actions.deleteWorkflowRun({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    run_id: run.id
                  });
                  console.log(`Deleted run: ${run.id} (${run.name})`);
                }
              }
            }
