---
name: Link Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RELEVANT_FILES: "README.md index.rst conf.py .readthedocs.yaml"

jobs:
  check-content-changes:
    name: Check for Relevant Changes
    runs-on: ubuntu-latest
    outputs:
      relevant_changed: ${{ steps.check.outputs.relevant_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Check changed files
        id: check
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            if ! git diff --quiet HEAD^ -- ${{ env.RELEVANT_FILES }} \
            $(git ls-files '**/*.jpg') || \
              git describe --exact-match &> /dev/null; then
              echo "relevant_changed=true" >> $GITHUB_OUTPUT
            else
              echo "relevant_changed=false" >> $GITHUB_OUTPUT
            fi
           fi

  link-check:
    name: Check Links
    needs: check-content-changes
    if: needs.check-content-changes.outputs.relevant_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Lychee
        run: |
          curl -LsSf https://github.com/lycheeverse/lychee/releases/latest/download/lychee-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv lychee /usr/local/bin/

      - name: Run Link Checker
        run: lychee --config .lychee.toml README.md

      - name: Archive Link Report
        uses: actions/upload-artifact@v5
        with:
          name: lychee-report
          path: lychee.out

  trigger-docs-build:
    name: Trigger Docs Build
    needs: link-check
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ReadTheDocs
        run: |
          curl -X POST \
            -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
            https://readthedocs.org/api/v3/projects/riay/versions/latest/builds/
